FROM openjdk:8

EXPOSE 8080

LABEL maintainer="UC Davis DSS IT http://it.dss.ucdavis.edu"

ARG IPA_DATASOURCE_URL=""
ENV IPA_DATASOURCE_URL $IPA_DATASOURCE_URL
ARG IPA_DATASOURCE_USERNAME=""
ENV IPA_DATASOURCE_USERNAME $IPA_DATASOURCE_USERNAME
ARG IPA_DATASOURCE_PASSWORD=""
ENV IPA_DATASOURCE_PASSWORD $IPA_DATASOURCE_PASSWORD

ENV IPA_SPRING_PROFILE="development"
ENV IPA_JWT_SIGNING_KEY="changeme"
ENV IPA_JWT_TIMEOUT=60
ENV IPA_URL_API=""
ENV DW_URL=""
ENV DW_TOKEN=""
ENV DW_PORT=""
ENV SMTP_HOST=""
ENV SMTP_EMAIL_FROM=""
ENV IPA_URL_FRONTEND=""
ENV CAS_URL=""

WORKDIR /app

ADD ./dw.dss.ucdavis.edu.cer dw.dss.ucdavis.edu.cer
RUN keytool -import -noprompt -trustcacerts -alias dss_dw -file dw.dss.ucdavis.edu.cer -storepass changeit -keystore "$JAVA_HOME/jre/lib/security/cacerts"

COPY ./gradle gradle
COPY ./gradlew gradlew
COPY ./build.gradle build.gradle

# RUN ./gradlew resolveDependencies

COPY ./src src

CMD ./gradlew build -x test
