FROM openjdk:8

MAINTAINER UC Davis DSS IT "http://it.dss.ucdavis.edu"

VOLUME /tmp
ADD ./build/libs/ipa-api-0.1.0.jar app.jar
RUN sh -c 'touch /app.jar'

ADD ./start.sh start.sh

ADD ./wait-for-it.sh wait-for-it.sh

# Needed for start.sh's MySQL readiness check
RUN apt-get update
RUN apt-get install -y mysql-client

ENTRYPOINT /bin/bash start.sh
