package edu.ucdavis.dss.ipa.entities.enums;

public enum BudgetSummary {
    TA_COUNT,
    TA_COST,
    READER_COUNT,
    READER_COST,
    LADDER_FACULTY_COST,
    EMERITI_COST,
    ASSOCIATE_INSTRUCTOR_COST,
    UNIT18_LECTURER_COST,
    CONTINUING_LECTURER_COST,
    VISITING_PROFESSOR_COST,
    INSTRUCTOR_COST,
    LECTURER_SOE_COST,
    UNASSIGNED_COST,
    LOWER_DIV_OFFERINGS,
    UPPER_DIV_OFFERINGS,
    GRAD_OFFERINGS,
    LOWER_DIV_SEATS,
    UPPER_DIV_SEATS,
    GRAD_SEATS,
    UNITS_OFFERED,
    SCH_UNDERGRAD,
    SCH_GRAD;
}
