# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          IPA_DATASOURCE_URL: jdbc:mysql://localhost/ipa_test
          IPA_DATASOURCE_USERNAME: root
          IPA_DATASOURCE_PASSWORD: testme
          IPA_URL_API: http://localhost:8080
          IPA_URL_FRONTEND: http://localhost:9000
          IPA_JWT_SIGNING_KEY: changeme
          IPA_JWT_TIMEOUT: 60
          CAS_URL: http://ssodev.ucdavis.edu/cas/
          AWS_ACCESS_KEY: changeme
          AWS_SECRET_KEY: changeme
          AWS_REGION: changeme
          AWS_S3_BUCKET: changeme
      - image: circleci/mysql:5.6.42
        environment:
          MYSQL_ROOT_PASSWORD: testme
          MYSQL_DATABASE: ipa_test

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx400m
      TERM: dumb
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      # run tests!
      - run: ./gradlew test

      - store_test_results:
          path: ~/repo/build/reports
      - store_artifacts:
          path: ~/repo/build/reports
