package edu.ucdavis.dss.ipa.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import org.springframework.data.annotation.Id;

@DynamoDBTable(tableName = "EventLogs")
public class EventLog {
    @Id
    private EventLogId eventLogId;

    private String entry;

    public EventLog() {
        // Default constructor is required by AWS DynamoDB SDK
    }

    public EventLog(EventLogId eventLogId, String entry) {
        this.eventLogId = eventLogId;
        this.entry = entry;
    }

    @DynamoDBRangeKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return eventLogId != null ? eventLogId.getId() : null;
    }

    public void setId(String id) {
        if (eventLogId == null) {
            eventLogId = new EventLogId();
        }
        eventLogId.setId(id);
    }

    @DynamoDBHashKey
    public String getLogEntityId() {
        return eventLogId != null ? eventLogId.getLogEntityId() : null;
    }

    public void setLogEntityId(String logEntityId) {
        if (eventLogId == null) {
            eventLogId = new EventLogId();
        }
        eventLogId.setLogEntityId(logEntityId);
    }

    @DynamoDBAttribute
    public String getEntry() {
        return entry;
    }

    public void setEntry(String entry) {
        this.entry = entry;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;
        EventLog event = (EventLog) o;
        return !(eventLogId != null ? !eventLogId.equals(event.eventLogId) : event.eventLogId != null);
    }

    @Override
    public int hashCode() {
        return eventLogId != null ? eventLogId.hashCode() : 0;
    }
}
