CREATE TABLE `ActivityLog` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `UsersId` INT(11) NOT NULL,
  `Message` VARCHAR(255) NOT NULL,
  `Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
  );

CREATE TABLE `ActivityLogTag` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ActivityLogId` INT(11) NOT NULL,
  `Tag` VARCHAR(50) NOT NULL
  );