ALTER TABLE `Sections` ADD COLUMN `UpdatedAt` TIMESTAMP NULL;
ALTER TABLE `Sections` ADD COLUMN `CreatedAt` TIMESTAMP NULL;
ALTER TABLE `Sections` ADD COLUMN `ModifiedBy` VARCHAR(16) NULL;

ALTER TABLE `Activities` ADD COLUMN `UpdatedAt` TIMESTAMP NULL;
ALTER TABLE `Activities` ADD COLUMN `CreatedAt` TIMESTAMP NULL;
ALTER TABLE `Activities` ADD COLUMN `ModifiedBy` VARCHAR(16) NULL;

ALTER TABLE `Courses` ADD COLUMN `UpdatedAt` TIMESTAMP NULL;
ALTER TABLE `Courses` ADD COLUMN `CreatedAt` TIMESTAMP NULL;
ALTER TABLE `Courses` ADD COLUMN `ModifiedBy` VARCHAR(16) NULL;

ALTER TABLE `SectionGroups` ADD COLUMN `UpdatedAt` TIMESTAMP NULL;
ALTER TABLE `SectionGroups` ADD COLUMN `CreatedAt` TIMESTAMP NULL;
ALTER TABLE `SectionGroups` ADD COLUMN `ModifiedBy` VARCHAR(16) NULL;

ALTER TABLE `Users` ADD COLUMN `UpdatedAt` TIMESTAMP NULL;
ALTER TABLE `Users` ADD COLUMN `CreatedAt` TIMESTAMP NULL;
ALTER TABLE `Users` ADD COLUMN `ModifiedBy` VARCHAR(16) NULL;

ALTER TABLE `UserRoles` ADD COLUMN `UpdatedAt` TIMESTAMP NULL;
ALTER TABLE `UserRoles` ADD COLUMN `CreatedAt` TIMESTAMP NULL;
ALTER TABLE `UserRoles` ADD COLUMN `ModifiedBy` VARCHAR(16) NULL;

ALTER TABLE `Workgroups` ADD COLUMN `UpdatedAt` TIMESTAMP NULL;
ALTER TABLE `Workgroups` ADD COLUMN `CreatedAt` TIMESTAMP NULL;
ALTER TABLE `Workgroups` ADD COLUMN `ModifiedBy` VARCHAR(16) NULL;