ALTER TABLE `InstructorCosts` ADD COLUMN `UpdatedAt` TIMESTAMP NULL;
ALTER TABLE `InstructorCosts` ADD COLUMN `CreatedAt` TIMESTAMP NULL;
ALTER TABLE `InstructorCosts` ADD COLUMN `ModifiedBy` VARCHAR(16) NULL;

ALTER TABLE `Budgets` ADD COLUMN `UpdatedAt` TIMESTAMP NULL;
ALTER TABLE `Budgets` ADD COLUMN `CreatedAt` TIMESTAMP NULL;
ALTER TABLE `Budgets` ADD COLUMN `ModifiedBy` VARCHAR(16) NULL;

ALTER TABLE `BudgetScenarios` ADD COLUMN `UpdatedAt` TIMESTAMP NULL;
ALTER TABLE `BudgetScenarios` ADD COLUMN `CreatedAt` TIMESTAMP NULL;
ALTER TABLE `BudgetScenarios` ADD COLUMN `ModifiedBy` VARCHAR(16) NULL;

ALTER TABLE `SectionGroupCosts` ADD COLUMN `UpdatedAt` TIMESTAMP NULL;
ALTER TABLE `SectionGroupCosts` ADD COLUMN `CreatedAt` TIMESTAMP NULL;
ALTER TABLE `SectionGroupCosts` ADD COLUMN `ModifiedBy` VARCHAR(16) NULL;

ALTER TABLE `SectionGroupCostComments` ADD COLUMN `UpdatedAt` TIMESTAMP NULL;
ALTER TABLE `SectionGroupCostComments` ADD COLUMN `CreatedAt` TIMESTAMP NULL;
ALTER TABLE `SectionGroupCostComments` ADD COLUMN `ModifiedBy` VARCHAR(16) NULL;

ALTER TABLE `LineItems` ADD COLUMN `UpdatedAt` TIMESTAMP NULL;
ALTER TABLE `LineItems` ADD COLUMN `CreatedAt` TIMESTAMP NULL;
ALTER TABLE `LineItems` ADD COLUMN `ModifiedBy` VARCHAR(16) NULL;

ALTER TABLE `LineItemComments` ADD COLUMN `UpdatedAt` TIMESTAMP NULL;
ALTER TABLE `LineItemComments` ADD COLUMN `CreatedAt` TIMESTAMP NULL;
ALTER TABLE `LineItemComments` ADD COLUMN `ModifiedBy` VARCHAR(16) NULL;