on:
  push:
    branches:
      - master

name: Deploy to Amazon ECS

jobs:
  build:
    uses:
      ucdavis-lsit/actions/.github/workflows/deploy.yml@main
    with:
      cluster: 'legacy'
      repo: 'ipa-web-prod'
      certificate: 'us-west-2-bundle'
      service: 'ipa-web-prod'
    secrets:
      access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-rds-cert: ${ secrets.RDS_US_WEST_2_BUNDLE_PEM }}
