on:
  push:
    branches:
      - master
  workflow_dispatch:

name: Push image to ECR and force new ECS deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Copy regional certificate bundle
        run: 'echo $RDS_US_WEST_2_BUNDLE_PEM | base64 -d > us-west-2-bundle.pem'
        shell: bash
        env:
          RDS_US_WEST_2_BUNDLE_PEM: ${{secrets.RDS_US_WEST_2_BUNDLE_PEM}}

      - name: Deploy
        uses: ucdavis-lsit/actions/.github/workflows/deploy.yml@main
        with:
          cluster: 'legacy'
          repo: 'ipa-web-staging'
          service: 'ipa-web-staging'
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
