on:
  push:
    branches:
      - master

name: Push image to ECR and force new ECS deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Copy regional certificate bundle
        run: 'echo $RDS_US_WEST_2_BUNDLE_PEM | base64 -d > us-west-2-bundle.pem'
        shell: bash
        env:
          RDS_US_WEST_2_BUNDLE_PEM: ${{secrets.RDS_US_WEST_2_BUNDLE_PEM}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and redeploy
        uses: jaroldwong/ecr-push-and-ecs-deploy@v1
        with:
          ecr-registry: ${{ steps.login-ecr.outputs.registry }}
          ecr-repository: 'ipa-web-prod'
          ecs-cluster: 'legacy'
          ecs-service: 'ipa-web-prod'
